release update and blog post for 2.21.0
geoserver/geoserver.github.io pull request #125
Opened 2022-05-24 09:36 UTC by ianturton

Please add any other sponsors that you would like to thank.

2022-05-24 09:51 UTC, bradh reviewed
A few minor comments.

2022-05-24 09:51 UTC, bradh commented on _posts/2022-05-24-geoserver-2-21-0-released.md
> +Thanks to Fernando Mino (GeoSolutions Group) for troubleshooting this performance issue, and proposal [GSIP-205](https://github.com/geoserver/geoserver/wiki/GSIP-204) as an optimization.
```suggestion
Thanks to Fernando Mino (GeoSolutions Group) for troubleshooting this performance issue, and proposal [GSIP-204](https://github.com/geoserver/geoserver/wiki/GSIP-204) as an optimization.
```
(I'm assuming this what was meant)

2022-05-24 09:51 UTC, bradh commented on _posts/2022-05-24-geoserver-2-21-0-released.md
> +Internally this release replaces changes from Log4j 1.2 logging profiles (using ``properties`` extension) to Log4j 2 logging profiles (using ``xml`` extension):
```suggestion
Internally this release changes from Log4j 1.2 logging profiles (using ``properties`` extension) to Log4j 2 logging profiles (using ``xml`` extension):
```

2022-05-24 09:51 UTC, bradh commented on _posts/2022-05-24-geoserver-2-21-0-released.md
> +For more information, and examples of writing on log4J 2 profile, see [Logging Settings](https://docs.geoserver.org/latest/en/user/configuration/globalsettings.html#logging-settings) and [Advanced lo
```suggestion
For more information, and examples of writing a Log4J 2 profile, see [Logging Settings](https://docs.geoserver.org/latest/en/user/configuration/globalsettings.html#logging-settings) and [Advanced log configuration](https://docs.geoserver.org/latest/en/user/configuration/logging.html) in the User Guide. Of note is the introduction of a new ``CONFIG`` logging level used when loading and saving configuration changes.
```

2022-05-24 09:51 UTC, bradh commented on _posts/2022-05-24-geoserver-2-21-0-released.md
> +* [GEOS-10426](https://osgeo-org.atlassian.net/browse/GEOS-10426) GISP 167: Upgrade Log4j
```suggestion
* [GEOS-10426](https://osgeo-org.atlassian.net/browse/GEOS-10426) GSIP 167: Upgrade Log4j
```

2022-05-24 09:51 UTC, bradh commented on _posts/2022-05-24-geoserver-2-21-0-released.md
> +  See [WPS Security and input limits](https://docs.geoserver.org/main/en/user/services/wps/security.html#complex-inputs) in User Guide.
```suggestion
  See [WPS Security and input limits](https://docs.geoserver.org/main/en/user/services/wps/security.html#complex-inputs) in the User Guide.
```

2022-05-25 04:01 UTC, jodygarnett requested changes
Minor suggestions below, really we want to provide an opportunity for @simboss and @aaime to thank any customers interested in being acknowledged.

2022-05-25 04:01 UTC, jodygarnett commented on _posts/2022-05-24-geoserver-2-21-0-released.md
> +
```suggestion

Thanks to the GeoNode project for these WPS improvements.
```

2022-05-25 09:42 UTC, aaime reviewed
Some more sponsors thanks.

2022-05-25 09:42 UTC, aaime commented on _posts/2022-05-24-geoserver-2-21-0-released.md
> +Thanks to Andrea Aime (GeoSolutions) for proposal [GSIP-207](https://github.com/geoserver/geoserver/wiki/GSIP-207) and implementation.
```suggestion
Thanks to Andrea Aime (GeoSolutions) for proposal [GSIP-207](https://github.com/geoserver/geoserver/wiki/GSIP-207) and implementation, and Canton of Solothurn for funding the work.
```

2022-05-25 09:42 UTC, aaime commented on _posts/2022-05-24-geoserver-2-21-0-released.md
> +Thanks to Yalın Eren Deliorman for this contribution.
```suggestion
Thanks to Yalın Eren Deliorman (GeoSolutions) for this contribution, and Eumetsat for sponsoring the work.
```

2022-05-25 09:42 UTC, aaime commented on _posts/2022-05-24-geoserver-2-21-0-released.md
> +* [GEOS-10443](https://osgeo-org.atlassian.net/browse/GEOS-10443) Graduate kml-ppio community module to wps extension
```suggestion
* [GEOS-10443](https://osgeo-org.atlassian.net/browse/GEOS-10443) Graduate kml-ppio community module to wps extension. Thanks to GeoSolutions for taking the maintainership of the module, and Masego Inc. for sponsoring the graduation work.
```

2022-05-25 09:42 UTC, aaime commented on _posts/2022-05-24-geoserver-2-21-0-released.md
> +Thanks to Fernando Mino (GeoSolutions Group) for troubleshooting this performance issue, and proposal [GSIP-204](https://github.com/geoserver/geoserver/wiki/GSIP-204) as an optimization.
```suggestion
Thanks to Fernando Mino (GeoSolutions Group) for troubleshooting this performance issue, and proposal [GSIP-204](https://github.com/geoserver/geoserver/wiki/GSIP-204) as an optimization. Thanks to EMSA for sponsoring the improvement.
```

2022-05-25 09:53 UTC, merged