Create 2024-02-01-geospatial-techno.md
geoserver/geoserver.github.io pull request #183
Opened 2024-01-30 20:37 UTC by geospatialtechno

Please review my content and let me know if any necessary corrections are needed.

2024-02-05 18:13 UTC, jodygarnett requested changes
Some minor feedback provided below.

Videos are great and accessible to people that do not wish to read instructions. That makes maintaining the instructions a bother.

Q: Can you think of anyway to minimize duplication with the user manual tutorials?

My concern is for visitors of the blog - as the blog post may become out of date, while the user manual tutorial matches the latest version.

**Suggestion:** We indicate which version of GeoServer this blog post was written for.

Q: If we want to make this look more consistent you could follow the user manual writing guide conventions:
- using "click" for links, and "press" for button
- Use **Save** (GUI elements are always **bold**)
- Navigate to **Data > Workspaces** page (we always call them pages)
- Use ``text`` to indicate content in lists to select
- Etc...

Writing conventions are important in a user manual where everything needs to be consistent. Blog post it is not so important so this is only for you to consider.

**Suggestion:** Please think about writing guidlines; I think if you did the **bold** for gui-elements and `text` for list and layer name selection it would be helpful. Following the same phrases as the user manual (click and press) are probably too much - as the blog post would not sound like your content and how you are speaking in the video.

2024-02-05 18:13 UTC, jodygarnett commented on _posts/2024-02-01-geospatial-techno.md
> +- DBF charset is used to decode strings from the dbf file, so it's very important to select an appropriate DBF character set.
I rarely have to use this option; I think it is only needed as an "override" when the shape file could not figure it out?

> DBF charset can be supplied, the character set could not be determined correctly from the DBF file

2024-02-12 16:19 UTC, geospatialtechno reviewed
@jodygarnett I have made the edits to this blog post according to your instructions.
Thanks for reviewing it

2024-02-13 18:25 UTC, jodygarnett commented
Thanks, I will review this morning

2024-02-16 08:03 UTC, jodygarnett commented
Thanks for waiting; I finally have my mkdocs conversion "done" (content not navigation) and can come up for air to breath.

2024-02-16 08:05 UTC, merged